anti_spoof_name: ['2.7_80x80_MiniFASNetV2', '4_0_0_80x80_MiniFASNetV1SE']

camera_url:

weights:
    face_detections:
        FaceDetector_480_onnx: https://drive.google.com/uc?id=1x7eeCvGesAHpEujRDJeQoBATqRHaiN6p&export=download
        FaceDetector_640_onnx: https://drive.google.com/uc?id=1JmiqwvLibzAVO863_FpUNhefkD2r_hiU&export=download
    embedding_models:
        ArcFace_R50_onnx: https://drive.google.com/uc?id=117NH1r0bJQs3q88KKNU3X7-6RTtLQHCe&export=download
    anti_spoof_models:
        2.7_80x80_MiniFASNetV2: https://drive.google.com/uc?id=1hWihYFCbK1zutOk-ZhZVsbvjGGomGti1&export=download
        4_0_0_80x80_MiniFASNetV1SE: https://drive.google.com/uc?id=1LQRhqSNAKiNSLtYb_KClT2TGJg06vrsA&export=download

postgres_db:
  host: localhost
  user: postgres
  password: postgres
  database: FaceRecognition_Project
  port: 5432
